- Dockerfile
Updated to latest version for .Net 6.0.
https://dotnet.microsoft.com/en-us/download/dotnet/6.0
> Updated to latest .net base images.

- .github/dependabot.yml
- Ignoring major updates. Do we want to continue with this pratcice?
> added dependabot 

- src/Register/Program.cs
> updated ai registration

- Dockerfile
Weekly update of container images used when building Register
> Update both base images for .Net

- Dockerfile
> Change entrypoint Dockerfile

- test/Altinn.Register.Tests.csproj
Remaining patching for week 39.
> Update nuget package versions

- .github/workflows/build-and-analyze.yml
- src/Altinn.Register.csproj
- src/Program.cs
> Replaced depreacted Azure dependencies

- src/Altinn.Register.csproj
> patched altinn.common.accesstoken

- src/Services/Implementation/PartiesWrapper.cs
- test/IntegrationTests/PartiesControllerTests.cs
> updated json namingpolicy to case insensitive

- Dockerfile
- src/Altinn.Register.csproj
- test/Altinn.Register.Tests.csproj
> bump to .net7

- src/Altinn.Register.csproj
This change updates Register to the latest preview version of AccessToken. This is to test the changes for a few days in AT.
> Update AccessToken library

- src/Altinn.Register.csproj
Bump AccessToken to latest version.
> Bump AccessToken

- src/Altinn.Register.csproj
- src/Program.cs
- test/IntegrationTests/Utils/WebApplicationFactorySetup.cs
- test/Mocks/PublicSigningKeyProviderMock.cs
- test/TestingControllers/OrganizationsControllerTests.cs
- test/TestingControllers/PartiesControllerTests.cs
Test release for the preview version of the AccessToken library. 
- https://github.com/Altinn/altinn-accesstoken/issues/25
> Bump AccessToken package reference

- Dockerfile
- test/Altinn.Register.Tests.csproj
> Patching w 24

- src/Altinn.Register.csproj
- src/Configuration/GeneralSettings.cs
- src/Configuration/PlatformSettings.cs
- src/Core/PersonLookupService.cs
- src/Extensions/HttpClientExtension.cs
- src/Program.cs
- src/Services/Implementation/PartiesWrapper.cs
- src/Services/Implementation/PersonsWrapper.cs
- src/Services/Interfaces/IParties.cs
- src/Services/Interfaces/IPersons.cs
- test/IntegrationTests/PartiesControllerTests.cs
- test/IntegrationTests/PersonsControllerTests.cs
- test/IntegrationTests/Utils/WebApplicationFactorySetup.cs
- test/UnitTests/PersonLookupServiceTests.cs
- test/UnitTests/PersonsWrapperTests.cs
The party API doesn't include first name and last name of the person. Changing which API we use should fix this.
- #89 
- #93
> Rewrite person lookup to use persons API

- .github/workflows/build-and-analyze-fork.yml
- .github/workflows/build-and-analyze.yml
- .github/workflows/codeql-analysis.yml
- Dockerfile
- src/Altinn.Register.csproj
- test/Altinn.Register.Tests.csproj
> upgraded solution to .net 8

- src/appsettings.json
Changed the number of attempts to 3. Verified OK with JVS/EM
> Fixed attempts to 3. Verified ok with JVS

- src/Altinn.Register.csproj
- src/Core/TooManyFailedLookupsException.cs
- test/Altinn.Register.Tests.csproj
- test/IntegrationTests/PartiesControllerTests.cs
Test preview versions of AccessToken and JWTCookieAuthentication.
- https://github.com/Altinn/altinn-accesstoken/issues/74
> Bump AccessToken and JWTCookieAuthentication

- src/Altinn.Register/Clients/BridgeOrgContactPointLookup.cs
- src/Altinn.Register/Clients/BridgeOrgContactPoints.cs
- src/Altinn.Register/Clients/Interfaces/IOrganizationClient.cs
- src/Altinn.Register/Clients/OrganizationClient.cs
- src/Altinn.Register/Services/Implementation/OrgContactPointService.cs
- src/Altinn.Register/Services/Interfaces/IOrgContactPoint.cs
Separate model to communicate with bridge. 
- altinn/altinn-notifications#450
> separate model for register client

- src/Altinn.Register/Clients/PartiesClient.cs
- src/Altinn.Register/Controllers/PartiesController.cs
- test/Altinn.Register.Tests/UnitTests/PartiesClientTest.cs
> chore: lookup parties by orgno/ssn in batch

- .github/workflows/publish-release.yml
Moving the if check to job level to skip more steps
> Move if check in workflow

- .github/scripts/publish-to-github-packages.mts
- .github/scripts/publish-to-nuget.mts
- .github/scripts/upload-packages-to-release.mts
- .github/workflows/release-please.yml
- .release-please-manifest.json
- .vscode/settings.json
- Directory.Build.props
- Directory.Build.targets
- release-please-config.json
- src/Altinn.Platform.Models/src/Altinn.Platform.Models/Altinn.Platform.Models.csproj
- src/Altinn.Register/src/Directory.Build.props
> ci: setup release-please

- src/Altinn.Register/test/.editorconfig
> chore: disable fluent assertions analyzer for old tests

- src/Altinn.Register/src/Altinn.Register/Clients/Interfaces/IOrganizationClient.cs
- src/Altinn.Register/src/Altinn.Register/Clients/Interfaces/IPersonClient.cs
- src/Altinn.Register/src/Altinn.Register/Clients/OrganizationClient.cs
- src/Altinn.Register/src/Altinn.Register/Clients/PersonClient.cs
- src/Altinn.Register/src/Altinn.Register/Controllers/OrgContactPointController.cs
- src/Altinn.Register/src/Altinn.Register/Controllers/OrganizationsController.cs
- src/Altinn.Register/src/Altinn.Register/Controllers/PartiesController.cs
- src/Altinn.Register/src/Altinn.Register/Controllers/PersonsController.cs
- src/Altinn.Register/src/Altinn.Register/Core/IPersonLookup.cs
- src/Altinn.Register/src/Altinn.Register/Core/PersonLookupService.cs
- src/Altinn.Register/src/Altinn.Register/Program.cs
- src/Altinn.Register/src/Altinn.Register/Services/Implementation/OrgContactPointService.cs
- src/Altinn.Register/src/Altinn.Register/Services/Interfaces/IOrgContactPoint.cs
- src/Altinn.Register/src/Altinn.Register/Services/PersonLookupCacheDecorator.cs
- src/Altinn.Register/test/Altinn.Register.Tests/TestingControllers/OrgContactPointControllerTests.cs
- src/Altinn.Register/test/Altinn.Register.Tests/TestingControllers/OrganizationsControllerTests.cs
- src/Altinn.Register/test/Altinn.Register.Tests/UnitTests/PersonLookupCacheDecoratorTests.cs
- src/Altinn.Register/test/Altinn.Register.Tests/UnitTests/PersonLookupServiceTests.cs
> chore: make controllers api controllers

- src/Altinn.Register/src/Altinn.Register/Clients/PartiesClient.cs
- src/Altinn.Register/src/Altinn.Register/Controllers/PartiesController.cs
- src/Altinn.Register/src/Altinn.Register/Core/PersonLookupService.cs
- src/Altinn.Register/test/Altinn.Register.Tests/Mocks/Authentication/JwtCookiePostConfigureOptionsStub.cs
- src/Altinn.Register/test/Altinn.Register.Tests/UnitTests/AsyncEnumerableExtensionsTests.cs
chore: try to fix flaky test
- #{issue number}
> chore: resolve more sonarcloud issues

- src/Altinn.Register/src/Altinn.Register.Persistence/Migration/v0.02-party-source-values/00-party-source-values.sql
> chore: fix party_source typo

- src/Altinn.Register/src/Altinn.Register.Persistence/Migration/v0.05-party-source-ref-index/00-party-source-ref-index.sql
> chore: add party-source-ref indices

- src/Altinn.Register/src/Altinn.Register.AppHost/Program.cs
> chore: remove unneeded code

- src/Altinn.Register/src/Altinn.Register.Persistence/Migration/v0.06-schema-grant/00-schema-grant.sql
> fix: schema grant

- src/Altinn.Register/src/Altinn.Register.Persistence/Microsoft.Extensions.Hosting/RegisterPersistenceExtensions.cs
> style: better marker registering

- Directory.Packages.props
- src/Altinn.Register/src/Altinn.Register.Core/Altinn.Register.Core.csproj
- src/Altinn.Register/src/Altinn.Register.Core/Microsoft.Extensions.DependencyInjection/UnitOfWorkServiceCollectionExtensions.cs
- src/Altinn.Register/src/Altinn.Register.Core/Parties/IPartyPersistence.cs
- src/Altinn.Register/src/Altinn.Register.Core/Parties/IV1PartyService.cs
- src/Altinn.Register/src/Altinn.Register.Core/RegisterActivitySource.cs
- src/Altinn.Register/src/Altinn.Register.Core/UnitOfWork/IUnitOfWork.cs
- src/Altinn.Register/src/Altinn.Register.Core/UnitOfWork/IUnitOfWorkManager.cs
- src/Altinn.Register/src/Altinn.Register.Core/UnitOfWork/IUnitOfWorkParticipant.cs
- src/Altinn.Register/src/Altinn.Register.Core/UnitOfWork/IUnitOfWorkParticipantFactory.cs
- src/Altinn.Register/src/Altinn.Register.Core/UnitOfWork/IUnitOfWorkServiceFactory.cs
- src/Altinn.Register/src/Altinn.Register.Core/UnitOfWork/UnitOfWorkExtensions.cs
- src/Altinn.Register/src/Altinn.Register.Core/UnitOfWork/UnitOfWorkManager.cs
- src/Altinn.Register/src/Altinn.Register.Core/UnitOfWork/UnitOfWorkStatus.cs
- src/Altinn.Register/src/Altinn.Register.Persistence/Altinn.Register.Persistence.csproj
- src/Altinn.Register/src/Altinn.Register.Persistence/Microsoft.Extensions.Hosting/RegisterPersistenceExtensions.cs
- src/Altinn.Register/src/Altinn.Register.Persistence/PostgreSqlPartyPersistence.cs
- src/Altinn.Register/src/Altinn.Register.Persistence/UnitOfWork/NpgsqlUnitOfWorkParticipant.cs
- src/Altinn.Register/src/Altinn.Register/Altinn.Register.csproj
- src/Altinn.Register/src/Altinn.Register/Clients/PartiesClient.cs
- src/Altinn.Register/src/Altinn.Register/Controllers/PartiesController.cs
- src/Altinn.Register/src/Altinn.Register/RegisterHost.cs
- src/Altinn.Register/test/Altinn.Register.Persistence.Tests/DatabaseTestBase.cs
- src/Altinn.Register/test/Altinn.Register.Persistence.Tests/NpgsqlUnitOfWorkTests.cs
- src/Altinn.Register/test/Altinn.Register.TestUtils/PostgreSqlDatabase.cs
- src/Altinn.Register/test/Altinn.Register.Tests/IntegrationTests/Utils/WebApplicationFactorySetup.cs
- src/Altinn.Register/test/Altinn.Register.Tests/TestingControllers/PartiesControllerTests.cs
> chore: add unit of work

- src/Altinn.Register/src/Altinn.Register.Core/Parties/MailingAddress.cs
- src/Altinn.Register/src/Altinn.Register.Core/Parties/StreetAddress.cs
- src/Altinn.Register/src/Altinn.Register.Persistence/Microsoft.Extensions.Hosting/RegisterPersistenceExtensions.cs
- src/Altinn.Register/src/Altinn.Register.Persistence/NpgsqlExtensions.cs
- src/Altinn.Register/test/Altinn.Register.Persistence.Tests/DataSourceMappingsTests.cs
> feat: add npgsql mapping for address types

- .editorconfig
- src/Altinn.Register/src/Altinn.Register.Core/Altinn.Register.Core.csproj
- src/Altinn.Register/src/Altinn.Register.Core/Parties/IPartyPersistence.cs
- src/Altinn.Register/src/Altinn.Register.Core/Parties/Organization.cs
- src/Altinn.Register/src/Altinn.Register.Core/Parties/Party.cs
- src/Altinn.Register/src/Altinn.Register.Core/Parties/PartyFieldIncludes.cs
- src/Altinn.Register/src/Altinn.Register.Core/Parties/Person.cs
- src/Altinn.Register/src/Altinn.Register.Core/Parties/Records/OrganizationRecord.cs
- src/Altinn.Register/src/Altinn.Register.Core/Parties/Records/PartyRecord.cs
- src/Altinn.Register/src/Altinn.Register.Core/Parties/Records/PersonRecord.cs
- src/Altinn.Register/src/Altinn.Register.Core/Utils/EnumExtensions.cs
- src/Altinn.Register/src/Altinn.Register.Core/Utils/FieldValue.cs
- src/Altinn.Register/src/Altinn.Register.Persistence/AsyncEnumerables/AsyncDisposableCollection.cs
- src/Altinn.Register/src/Altinn.Register.Persistence/AsyncEnumerables/FailedEnumerable.cs
- src/Altinn.Register/src/Altinn.Register.Persistence/AsyncEnumerables/IAsyncResourceOwner.cs
- src/Altinn.Register/src/Altinn.Register.Persistence/AsyncEnumerables/RegisterPersistenceAsyncEnumerableExtensions.cs
- src/Altinn.Register/src/Altinn.Register.Persistence/AsyncEnumerables/ResourceOwningEnumerable.cs
- src/Altinn.Register/src/Altinn.Register.Persistence/AsyncEnumerables/ThrowingAsyncEnumerable.cs
- src/Altinn.Register/src/Altinn.Register.Persistence/NpgsqlExtensions.cs
- src/Altinn.Register/src/Altinn.Register.Persistence/PostgreSqlPartyPersistence.PartyQuery.cs
- src/Altinn.Register/src/Altinn.Register.Persistence/PostgreSqlPartyPersistence.cs
- src/Altinn.Register/src/Altinn.Register/Altinn.Register.csproj
- src/Altinn.Register/test/Altinn.Register.Persistence.Tests/PostgreSqlPartyPersistenceTests.cs
- src/Altinn.Register/test/Altinn.Register.Persistence.Tests/ThrowingAsyncEnumerableTests.cs
- src/Altinn.Register/test/Altinn.Register.TestUtils/Altinn.Register.TestUtils.csproj
- src/Altinn.Register/test/Altinn.Register.TestUtils/Assertions/CustomFluentAssertionExtensions.cs
- src/Altinn.Register/test/Altinn.Register.TestUtils/Assertions/FieldValueAssertions.cs
> feat: read party from db

- src/Altinn.Register/src/Altinn.Register.Core/Microsoft.Extensions.DependencyInjection/UnitOfWorkServiceCollectionExtensions.cs
- src/Altinn.Register/src/Altinn.Register.Core/Parties/IPartyRolePersistence.cs
- src/Altinn.Register/src/Altinn.Register.Core/Parties/LangCode.cs
- src/Altinn.Register/src/Altinn.Register.Core/Parties/PartyFieldIncludes.cs
- src/Altinn.Register/src/Altinn.Register.Core/Parties/PartyRoleFieldIncludes.cs
- src/Altinn.Register/src/Altinn.Register.Core/Parties/Records/PartyRoleRecord.cs
- src/Altinn.Register/src/Altinn.Register.Core/Parties/TranslatedText.Builder.cs
- src/Altinn.Register/src/Altinn.Register.Core/Parties/TranslatedText.cs
- src/Altinn.Register/src/Altinn.Register.Core/UnitOfWork/UnitOfWorkExtensions.cs
- src/Altinn.Register/src/Altinn.Register.Core/Utils/IConvertibleFrom.cs
- src/Altinn.Register/src/Altinn.Register.Core/Utils/ListExtensions.cs
- src/Altinn.Register/src/Altinn.Register.Persistence/Microsoft.Extensions.Hosting/RegisterPersistenceExtensions.cs
- src/Altinn.Register/src/Altinn.Register.Persistence/NpgsqlExtensions.cs
- src/Altinn.Register/src/Altinn.Register.Persistence/PostgreSqlPartyPersistence.PartyRoleQuery.cs
- src/Altinn.Register/src/Altinn.Register.Persistence/PostgreSqlPartyPersistence.cs
- src/Altinn.Register/src/Altinn.Register/Clients/PartiesClient.cs
- src/Altinn.Register/test/Altinn.Register.Persistence.Tests/PostgreSqlPartyPersistenceTests.cs
- src/Altinn.Register/test/Altinn.Register.Tests/UnitTests/LangCodeTests.cs
- src/Altinn.Register/test/Altinn.Register.Tests/UnitTests/ListExtensionsTests.cs
- src/Altinn.Register/test/Altinn.Register.Tests/UnitTests/TranslatedTextTests.cs
- src/Altinn.Register/test/Altinn.Register.Tests/Utils/AsyncList.cs
> feat: add support for getting roles

- src/Altinn.Register/src/Altinn.Register.Core/Parties/OrganizationIdentifier.cs
- src/Altinn.Register/test/Altinn.Register.Tests/UnitTests/OrganizationIdentifierTests.cs
> chore: validate orgno

- src/Altinn.Register/src/Altinn.Register.Core/Parties/OrganizationIdentifier.cs
- src/Altinn.Register/src/Altinn.Register.Core/Parties/PersonIdentifier.cs
- src/Altinn.Register/test/Altinn.Register.Tests/UnitTests/PersonIdentifierTests.cs
> chore: validate person identifier

- Directory.Packages.props
- src/Altinn.Register/src/Altinn.Register.Core/Altinn.Register.Core.csproj
- src/Altinn.Register/src/Altinn.Register.Core/Errors/Problems.cs
- src/Altinn.Register/src/Altinn.Register.Core/Parties/IPartyPersistence.cs
- src/Altinn.Register/src/Altinn.Register.Core/Parties/OrganizationIdentifier.cs
- src/Altinn.Register/src/Altinn.Register.Core/Parties/Records/OrganizationRecord.cs
- src/Altinn.Register/src/Altinn.Register.Core/Parties/Records/PartyRecord.cs
- src/Altinn.Register/src/Altinn.Register.Core/Parties/Records/PersonRecord.cs
- src/Altinn.Register/src/Altinn.Register.Core/Utils/FieldValue.cs
- src/Altinn.Register/src/Altinn.Register.Persistence/PostgreSqlPartyPersistence.cs
- src/Altinn.Register/src/Altinn.Register.Persistence/UnitOfWork/ISavePoint.cs
- src/Altinn.Register/src/Altinn.Register.Persistence/UnitOfWork/NpgsqlUnitOfWorkParticipant.cs
- src/Altinn.Register/src/Altinn.Register.Persistence/UnitOfWork/SavePointManager.cs
- src/Altinn.Register/src/Altinn.Register.Persistence/Utils/AsyncLock.cs
- src/Altinn.Register/test/Altinn.Register.Persistence.Tests/PostgreSqlPartyPersistenceTests.cs
- src/Altinn.Register/test/Altinn.Register.TestUtils/Assertions/CustomAssertions.cs
- src/Altinn.Register/test/Altinn.Register.TestUtils/Assertions/CustomFluentAssertionExtensions.cs
- src/Altinn.Register/test/Altinn.Register.TestUtils/Assertions/FieldValueAssertions.cs
- src/Altinn.Register/test/Altinn.Register.TestUtils/Assertions/ResultAssertions.cs
> feat: upsert party

- .editorconfig
- Directory.Packages.props
- src/Altinn.Register/src/Altinn.Register.Persistence/NpgsqlExtensions.cs
- src/Altinn.Register/src/Altinn.Register/Altinn.Register.csproj
- src/Altinn.Register/src/Altinn.Register/Clients/PartiesClient.cs
- src/Altinn.Register/src/Altinn.Register/Controllers/DebugProxyController.cs
- src/Altinn.Register/src/Altinn.Register/Conventions/ConditionalControllerConvention.cs
- src/Altinn.Register/src/Altinn.Register/Conventions/DevTestConditionAttribute.cs
- src/Altinn.Register/src/Altinn.Register/Conventions/IControllerCondition.cs
- src/Altinn.Register/src/Altinn.Register/RegisterHost.cs
- src/Altinn.Register/src/Altinn.Register/appsettings.Development.json
- src/Altinn.Register/test/Altinn.Register.Tests/Mocks/MockMessageHandler.cs
- src/Altinn.Register/test/Altinn.Register.Tests/TestingControllers/DebugProxyControllerTests.cs
> chore: a2 changes proxy

- Directory.Packages.props
- src/Altinn.Register/src/Altinn.Register.Core/Leases/ILeaseProvider.cs
- src/Altinn.Register/src/Altinn.Register.Core/Leases/LeaseAcquireResult.cs
- src/Altinn.Register/src/Altinn.Register.Core/Leases/LeaseTicket.cs
- src/Altinn.Register/src/Altinn.Register.Persistence/Altinn.Register.Persistence.csproj
- src/Altinn.Register/src/Altinn.Register.Persistence/Leases/PostgresqlLeaseProvider.cs
- src/Altinn.Register/src/Altinn.Register.Persistence/Microsoft.Extensions.Hosting/RegisterPersistenceExtensions.cs
- src/Altinn.Register/src/Altinn.Register.Persistence/Migration/v0.08-leases/00-lease-table.sql
- src/Altinn.Register/test/Altinn.Register.Persistence.Tests/Leases/PostgresqlLeaseProviderTests.cs
> feat: leases

- Directory.Packages.props
- src/Altinn.Register/src/Altinn.Register.Core/Altinn.Register.Core.csproj
- src/Altinn.Register/src/Altinn.Register.Core/Leases/Lease.cs
- src/Altinn.Register/src/Altinn.Register.Core/Leases/LeaseManager.cs
- src/Altinn.Register/src/Altinn.Register.Core/Microsoft.Extensions.DependencyInjection/LeaseServiceCollectionExtensions.cs
- src/Altinn.Register/src/Altinn.Register/RegisterHost.cs
- src/Altinn.Register/test/Altinn.Register.Persistence.Tests/Leases/LeaseManagerTests.cs
> feat: lease manager

- src/Altinn.Register/src/Altinn.Register/Extensions/AsyncEnumerableExtensions.cs
- src/Altinn.Register/test/Altinn.Register.Tests/UnitTests/AsyncEnumerableExtensionsTests.cs
- src/Altinn.Register/test/Altinn.Register.Tests/Utils/AsyncEnumerableTestExtensions.cs
- src/Altinn.Register/test/Altinn.Register.Tests/Utils/AsyncList.cs
> refactor: improve async merge handling and performance

- src/Altinn.Register/src/Altinn.Register.Core/Utils/FieldValue.cs
- src/Altinn.Register/src/Altinn.Register.Persistence/ImportJobs/PostgresImportJobTracker.cs
- src/Altinn.Register/src/Altinn.Register.Persistence/Leases/PostgresqlLeaseProvider.cs
- src/Altinn.Register/src/Altinn.Register.Persistence/NpgsqlExtensions.cs
- src/Altinn.Register/src/Altinn.Register.Persistence/PostgreSqlPartyPersistence.PartyQuery.cs
- src/Altinn.Register/src/Altinn.Register.Persistence/PostgreSqlPartyPersistence.PartyRoleQuery.cs
- src/Altinn.Register/src/Altinn.Register.Persistence/PostgreSqlPartyPersistence.cs
- src/Altinn.Register/test/Altinn.Register.Persistence.Tests/DataSourceMappingsTests.cs
- src/Altinn.Register/test/Altinn.Register.Persistence.Tests/Leases/LeaseManagerTests.cs
- src/Altinn.Register/test/Altinn.Register.Persistence.Tests/PostgreSqlPartyPersistenceTests.cs
- src/Altinn.Register/test/Altinn.Register.Persistence.Tests/Utils/PartyPersistenceExtensions.cs
> chore: make all DB calls async

- src/Altinn.Register/src/Altinn.Register/PartyImport/A2/A2PartyImportService.cs
- src/Altinn.Register/test/Altinn.Register.Tests/PartyImport/A2/A2PartyImportServiceTests.cs
- src/Altinn.Register/test/Altinn.Register.Tests/PartyImport/A2PartyImportConsumerTests.cs
Ref #287 avklaring rundt person navn
> chore: generate display-name for persons

- src/pkgs/Altinn.Register.Contracts/README.md
> docs: update readme

- Directory.Packages.props
- src/apps/Altinn.Register/src/Altinn.Register/Altinn.Register.csproj
- src/apps/Altinn.Register/src/Altinn.Register/PartyImport/A2/A2PartyImportJob.cs
- src/apps/Altinn.Register/src/Altinn.Register/PartyImport/A2/A2PartyUserIdImportJob.cs
- src/apps/Altinn.Register/src/ServiceDefaults.Jobs/Altinn.Authorization.ServiceDefaults.Jobs.csproj
- src/apps/Altinn.Register/src/ServiceDefaults.Jobs/IJob.cs
- src/apps/Altinn.Register/src/ServiceDefaults.Jobs/IJobSettings.cs
- src/apps/Altinn.Register/src/ServiceDefaults.Jobs/Job.cs
- src/apps/Altinn.Register/src/ServiceDefaults.Jobs/JobHostLifecycles.cs
- src/apps/Altinn.Register/src/ServiceDefaults.Jobs/JobRegistration.cs
- src/apps/Altinn.Register/src/ServiceDefaults.Jobs/JobsTelemetry.cs
- src/apps/Altinn.Register/src/ServiceDefaults.Jobs/Microsoft.Extensions.DependencyInjection/JobsServiceCollectionExtensions.cs
- src/apps/Altinn.Register/src/ServiceDefaults.Jobs/RecurringJobHostedService.cs
- src/apps/Altinn.Register/test/Altinn.Register.Tests/Jobs/RecurringJobHostedServiceTests.cs
---
This is **part 1 of 2 in a stack** made with GitButler:
- <kbd>&nbsp;2&nbsp;</kbd> #523 
- <kbd>&nbsp;1&nbsp;</kbd> #522 👈
> chore: move jobs to separate project

- src/apps/Altinn.Register/src/Altinn.Register.Core/Utils/ByteSize.cs
- src/apps/Altinn.Register/test/Altinn.Register.Tests/UnitTests/ByteSizeTests.cs
---
This is **part 1 of 4 in a stack** made with GitButler:
- <kbd>&nbsp;4&nbsp;</kbd> #529 
- <kbd>&nbsp;3&nbsp;</kbd> #528 
- <kbd>&nbsp;2&nbsp;</kbd> #527 
- <kbd>&nbsp;1&nbsp;</kbd> #526 👈
> chore: bytesize util

- src/apps/Altinn.Register/src/Altinn.Register.Persistence/PostgreSqlSizeService.cs
- src/apps/Altinn.Register/test/Altinn.Register.Persistence.Tests/PostgreSqlSizeServiceTests.cs
---
This is **part 2 of 4 in a stack** made with GitButler:
- <kbd>&nbsp;4&nbsp;</kbd> #529 
- <kbd>&nbsp;3&nbsp;</kbd> #528 
- <kbd>&nbsp;2&nbsp;</kbd> #527 👈 
- <kbd>&nbsp;1&nbsp;</kbd> #526
> feat: pg size service

- src/apps/Altinn.Register/src/Altinn.Register.Persistence/Altinn.Register.Persistence.csproj
- src/apps/Altinn.Register/src/Altinn.Register.Persistence/Microsoft.Extensions.Hosting/RegisterPersistenceExtensions.cs
---
This is **part 4 of 4 in a stack** made with GitButler:
- <kbd>&nbsp;4&nbsp;</kbd> #529 👈 
- <kbd>&nbsp;3&nbsp;</kbd> #528 
- <kbd>&nbsp;2&nbsp;</kbd> #527 
- <kbd>&nbsp;1&nbsp;</kbd> #526
> feat: db size condition

- src/apps/Altinn.Register/src/Altinn.Register/Mapping/PartyMapper.PartyTypes.cs
- src/pkgs/Altinn.Register.Contracts/src/Altinn.Register.Contracts/EnterpriseUser.cs
- src/pkgs/Altinn.Register.Contracts/src/Altinn.Register.Contracts/PartyOwnerRef.cs
- src/pkgs/Altinn.Register.Contracts/src/Altinn.Register.Contracts/SystemUser.cs
- src/pkgs/Altinn.Register.Contracts/test/Altinn.Register.Contracts.Tests/EnterpriseUserTests.cs
- src/pkgs/Altinn.Register.Contracts/test/Altinn.Register.Contracts.Tests/PartyTests.cs
- src/pkgs/Altinn.Register.Contracts/test/Altinn.Register.Contracts.Tests/Snapshots/EnterpriseUserTests.MaximalEnterpriseUser.verified.json
- src/pkgs/Altinn.Register.Contracts/test/Altinn.Register.Contracts.Tests/Snapshots/SystemUserTests.MaximalSystemUser.verified.json
- src/pkgs/Altinn.Register.Contracts/test/Altinn.Register.Contracts.Tests/SystemUserTests.cs
---
This is **part 2 of 2 in a stack** made with GitButler:
- <kbd>&nbsp;2&nbsp;</kbd> #547 👈 
- <kbd>&nbsp;1&nbsp;</kbd> #546
> feat: add owner to contracts

- src/pkgs/Altinn.Register.Contracts/README.md
- src/pkgs/Altinn.Register.Contracts/src/Altinn.Register.Contracts/PartyType.cs
> fix: change PartyType to unsigned

- src/apps/Altinn.Register/src/Altinn.Register/Mapping/PartyMapper.PartyTypes.cs
- src/pkgs/Altinn.Register.Contracts/src/Altinn.Register.Contracts/PartyType.cs
- src/pkgs/Altinn.Register.Contracts/src/Altinn.Register.Contracts/SystemUser.cs
- src/pkgs/Altinn.Register.Contracts/src/Altinn.Register.Contracts/SystemUserType.cs
- src/pkgs/Altinn.Register.Contracts/test/Altinn.Register.Contracts.Tests/Snapshots/SystemUserTests.MaximalSystemUser_Agent.verified.json
- src/pkgs/Altinn.Register.Contracts/test/Altinn.Register.Contracts.Tests/SystemUserTests.cs
---
This is **part 1 of 2 in a stack** made with GitButler:
- <kbd>&nbsp;2&nbsp;</kbd> #587 
- <kbd>&nbsp;1&nbsp;</kbd> #586 👈
> feat: add system-user type

- src/apps/Altinn.Register/src/Altinn.Register/Mapping/PartyMapper.PartyTypes.cs
---
This is **part 2 of 2 in a stack** made with GitButler:
- <kbd>&nbsp;2&nbsp;</kbd> #587 👈 
- <kbd>&nbsp;1&nbsp;</kbd> #586
> fix: party mapping exception messages
